# Generated by Django 3.0.6 on 2020-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TITLE')),
                ('slug', models.SlugField(allow_unicode=True, help_text='슬러그 헬프', unique=True, verbose_name='SLUG')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('content', models.TextField(verbose_name='CONTENT')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('modify_dt', models.DateTimeField(auto_now=True, verbose_name='Modify Date')),
            ],
        ),
    ]
